-- General keymaps
require("core.utils").set_keys(_, {
    { "v", "<leader><leader>", "<esc>", "Exit visual mode" },
    { "n", "u", "<cmd>silent! undo<cr>", "Undo" },
    { "n", "<C-r>", "<cmd>silent! redo<cr>", "Redo" },
    { "i", "<C-k>", "<up>", "Move up" },
    { "i", "<C-j>", "<down>", "Move down" },
    { "i", "<C-h>", "<left>", "Move left" },
    { "i", "<C-l>", "<right>", "Move right" },
    { "v", ">", ">gv", "Indent right" },
    { "v", "<tab>", ">gv", "Indent right" },
    { "v", "<", "<gv", "Indent left" },
    { "v", "<S-tab>", "<gv", "Indent left" },
    { { "n", "i", "v" }, "<C-s>", "<cmd>silent! w!<CR>", "Save" },
    { { "n", "v" }, "<C-v>", '"+p', "Paste from clipboard" },
    { "i", "<C-v>", '<Esc>"+pa', "Paste from clipboard" },
    { "c", "<C-S-v>", "<C-R>+", "Paste in command mode" },
    { "v", "<C-c>", '"+y', "Copy to clipboard" },
    { "n", "<C-a>", "ggVG", "Select all" },
})
