name: Generate README for Plugins

on:
  push:
    paths:
      - "lua/plugins/**"
      - ".github/workflows/gen-readme.yml"
  workflow_dispatch:

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Lua
        uses: ljmf00/setup-lua@v1.0.0

      - name: Install jq for JSON parsing
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Run README generator
        shell: bash
        run: |
          mkdir -p .cache
          cp .github/workflows/README.header.md README.md
          echo "" >> README.md
          echo "_Last updated: $(date -u '+%Y-%m-%d %H:%M UTC')_" >> README.md
          echo "" >> README.md

          declare -A printed_plugins grouped_plugins

          # Quét tất cả plugin files (bỏ unused)
          find lua/plugins -type f -name '*.lua' | grep -v '/unused/' | while read plugin; do
            # Tìm tất cả "user/repo"
            grep -oE '"[a-zA-Z0-9_.-]+/[a-zA-Z0-9_.-]+"' "$plugin" | sed 's/"//g' | while read name; do
              # Bỏ nếu không phải GitHub repo (vd: /bin/bash hoặc $VIMRUNTIME)
              [[ "$name" == /* || "$name" == \$* ]] && continue

              # Bỏ nếu đã in
              if [[ -n "$name" && -z "${printed_plugins[$name]}" ]]; then
                printed_plugins["$name"]=1

                # Xác định group
                if [[ "$plugin" =~ lua/plugins/([^/]+)/ ]]; then
                  group="${BASH_REMATCH[1]}"
                else
                  group="Ungrouped"
                fi

                grouped_plugins["$group"]+="$name"$'\n'
              fi
            done
          done

          # Ghi từng nhóm vào README
          for group in "${!grouped_plugins[@]}"; do
            echo "## $(tr '[:lower:]' '[:upper:]' <<< ${group:0:1})${group:1} Plugins" >> README.md
            echo "" >> README.md
            echo "| Name | Description | Optional? |" >> README.md
            echo "| ---- | ----------- | --------- |" >> README.md

            while read name; do
              [ -z "$name" ] && continue

              cache_file=".cache/$(echo "$name" | sed 's|/|_|g').json"
              if [ -f "$cache_file" ]; then
                desc=$(jq -r '.description' "$cache_file")
              else
                curl -s "https://api.github.com/repos/$name" -o "$cache_file"
                desc=$(jq -r '.description' "$cache_file")
              fi

              [ "$desc" = "null" ] && desc=""

              # Check optional flag
              optional=""
              files=$(grep -rl "$name" lua/plugins | grep -v '/unused/' || true)
              for file in $files; do
                if grep -A5 "$name" "$file" | grep -qE 'optional\s*=\s*true'; then
                  optional="_Optional_"
                  break
                fi
              done

              echo "| [$name](https://github.com/$name) | $desc | $optional |" >> README.md
            done <<< "${grouped_plugins[$group]}"

            echo "" >> README.md
          done

      - name: Upload generated README
        uses: actions/upload-artifact@v4
        with:
          name: generated-readme
          path: README.md
